### ISSUE TITLE
CellID assignments above "999" do not track de same cell in time courses

### ISSUE THREAD

**Issue by naikymen** [naikymen/cellID-linux#2]
Scenario: every cell with cellid identifier greater than 999 will be assigned a different cellid on each subsequent t.frame.

**Comment by gaspanico** [comment]
Fixed by commenting these three lines in segment.c!

```
if ((cs[j]->index)>=tmp_j){
   continue; //No need to compare to id's above fret_offset
}
```

Commit fixing this is [8ccba98](https://github.com/darksideoftheshmoo/cellID-linux/commit/8ccba98c2f1063d62aca5f1a0109efb076aa94af), but I pushed an "empty" commit to close the issue.
