### ISSUE TITLE
BF as fluorescence ("bf as fl") repeats time frames.

### ISSUE THREAD

**Issue by gaspanico** [naikymen/cellID-linux#4]
This option does not work as expected with time course experiments. Except for the first time frame (which appears to work correctly), all following time frames are analyzed in a repeated manner. See example below, where a time course with only three time frames (t.frame : {0,1,2}) were included; t.frame==1 was repeated 16 times, and t.frame==2 32 times.

![Skärmavbild 2020-10-18 kl  18 05 51](https://user-images.githubusercontent.com/71889067/96385860-04871080-116d-11eb-858b-ace62c2b39b8.png)

A workaround for now is to simply copy the BF images and rename their prefix to XFP, where X can be any capital letter representing a free fluorescence channel. These images will then automatically be treated as fluorescence images, without having to activate this function in Cell-ID. Using this approach on the above experiment, copying the BF images as BFP, gives the following result:

![Skärmavbild 2020-10-18 kl  18 19 25](https://user-images.githubusercontent.com/71889067/96386174-592b8b00-116f-11eb-9059-5c4d7b9fda06.png)

Note how the values of both ```f.tot.b``` and ```f.nucl.b``` correspond well with the values calculated with "bf as fl".

The only potential drawback of this workaround is that it adds an additional set of redundant images, thereby increasing the size of the experiment. These extra images may however be deleted after running Cell-ID; keep in mind, however, that import into Rcell still retains the mapping of the ```XFP``` channel to these images, which could lead to errors when using functions such as ```cimage```.

**Comment by naikymen** [comment]
Fixed indeed :) 

![image](https://user-images.githubusercontent.com/3259326/159136310-c274e458-ba68-4098-859d-f5c13518feca.png)

Andy crack.
